### ISSUE TITLE
mac ???/1??

### ISSUE THREAD

**Issue by camila314** [Adrikikicp/Adrikikicp-SDK#1]
when is mac support coming. also ios and android, when is it? please make mac i will be your biggest fan if you can add mac

**Comment by altalk23** [comment]
please please port to 2.2 i want create noc lip hax with platformer roptob

**Comment by Cvolton** [comment]
![Among-Us-Red-Crewmate](https://user-images.githubusercontent.com/5721187/148438631-fcb5a327-09f6-45d4-8841-1aaa901da215.png)

**Comment by Adrikikicp** [comment]
impostor


Wontfix

**Comment by Adrikikicp** [comment]
Mac soon
